changes added

diff --git a/.github/workflows/building-blocks.yaml b/.github/workflows/building-blocks.yaml
--- a/.github/workflows/building-blocks.yaml
+++ b/.github/workflows/building-blocks.yaml
@@ -2,7 +2,7 @@ name: Building Blocks
 on:
     push:
         branches:
-        - main
+            - main
 jobs:
   echo-hello:
     runs-on: ubuntu-latest
@@ -14,7 +14,7 @@ jobs:
     steps:
       - name: Failed Step
         run: |
-            echo "This step will fail"
-            exit 1
+              echo "This step will fail"
+              exit 1
       - name: Say Goodbye
         run: echo "Goodbye, World!"
